version: '3'
services:

  azure-storage:
    image: video-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=narvaneflixtubestorage
      - STORAGE_ACCESS_KEY=R+XorTxImgOOz79tCEi+38Ip/NJwlJha/QEP/poz8nvZcctyYJMXu90CjrlDvD302IeieBUctCNB+ASt4Pf9PA==
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"